version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  web:
    build: ./multimodal_rag
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_KEYS=${API_KEYS}
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_DB_PATH=/data/chroma_db
      - CHECKPOINT_DIR=/data/checkpoints
      - INGEST_CACHE_DIR=/data/cache
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on: [redis]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: ./multimodal_rag
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_KEYS=${API_KEYS}
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_DB_PATH=/data/chroma_db
      - CHECKPOINT_DIR=/data/checkpoints
      - INGEST_CACHE_DIR=/data/cache
    volumes:
      - ./data:/data
    depends_on: [redis]
    # Linux: remove --pool=solo to get concurrency or use gevent/eventlet pools
    command:
      [
        "celery",
        "-A",
        "app.celery_app.celery_app",
        "worker",
        "-l",
        "INFO",
        "--pool=solo",
      ]
